# array input 和 output


In [1]:
import numpy as np

In [2]:
import pickle

In [22]:
x = np.arange(10)

In [23]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
f = open('x.pkl','wb')

In [25]:
pickle.dump(x,f)

In [26]:
!ls

array input 和 output.ipynb    x.pkl
array.ipynb                    数组与矩阵的运算.ipynb


In [27]:
r = open('x.pkl','rb')

In [28]:
pickle.load(r)

EOFError: Ran out of input

In [29]:
np.save('one_arry',x) # 存储

In [30]:
!ls

array input 和 output.ipynb    x.pkl
array.ipynb                    数组与矩阵的运算.ipynb
one_arry.npy


In [31]:
np.load('one_arry.npy') #读取

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
y = np.arange(20)

In [33]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
np.savez('two_array',a=x,b=y)

In [35]:
!ls

array input 和 output.ipynb    two_array.npz
array.ipynb                    x.pkl
one_arry.npy                   数组与矩阵的运算.ipynb


In [36]:
c = np.load('two_array.npz')

In [37]:
c

In [41]:
c['a'],c['b']

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]))