In [1]:
from pandas import Series

In [4]:
import pandas as pd
import numpy as np

In [5]:
s1 = Series([1,2,3,4]) # 第一种创建Series的方式

In [7]:
s1 # 第一列是index 第二列是值

0    1
1    2
2    3
3    4
dtype: int64

In [8]:
s1.values # 获取值

array([1, 2, 3, 4])

In [9]:
s1.index 

RangeIndex(start=0, stop=4, step=1)

In [10]:
s2 = Series(np.arange(10)) # 第二种创建Series的方式

In [11]:
s2

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [12]:
s3 = Series({'2':1,'3':3}) # 第三种创建 Series的方式

In [13]:
s3

2    1
3    3
dtype: int64

In [14]:
s3.index

Index(['2', '3'], dtype='object')

In [15]:
s3.values

array([1, 3])

In [18]:
# 指定index

s4 = Series([1,2,3,4],index=['a','b','c','d'])

In [20]:
s4.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [21]:
s4.values

array([1, 2, 3, 4])

In [22]:
s4.value_counts

<bound method IndexOpsMixin.value_counts of a    1
b    2
c    3
d    4
dtype: int64>

In [23]:
# 根据 索引 获取值

In [26]:
s4['a']

1

In [27]:
s4[s4>2]

c    3
d    4
dtype: int64

In [30]:
s4.to_dict() # 转换成字典

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [31]:
s5 = Series(s4.to_dict())

In [32]:
s5

a    1
b    2
c    3
d    4
dtype: int64

In [39]:
s6 = Series(s5,index=['a',"b","C","D","E"])

In [40]:
s6

a    1.0
b    2.0
C    NaN
D    NaN
E    NaN
dtype: float64

In [41]:
pd.isnull(s6) # 判断是不是NUll

a    False
b    False
C     True
D     True
E     True
dtype: bool

In [42]:
pd.notnull(s6)

a     True
b     True
C    False
D    False
E    False
dtype: bool

In [43]:
s6.name = 'demo'

In [45]:
s6.index.name = 'demo index'

In [46]:
s6

demo index
a    1.0
b    2.0
C    NaN
D    NaN
E    NaN
Name: demo, dtype: float64