# 快速创建数组

In [1]:
import numpy as np

In [2]:
np.random.randn(10)

array([ 0.67118554, -0.34334482,  0.82818588, -1.50158577,  0.66528436,
        0.46983702, -0.93442089, -0.28250935, -1.12411095,  0.4941913 ])

In [3]:
# 返回随机数

In [4]:
np.random.randint(10)

4

In [7]:
np.random.randint(10,size=20) 

array([0, 3, 8, 2, 5, 0, 0, 7, 8, 7, 8, 9, 0, 8, 5, 7, 3, 3, 4, 6])

In [8]:
np.random.randint(10,size=20).reshape(4,5) # 变多维数组

array([[4, 1, 3, 8, 5],
       [2, 5, 6, 4, 5],
       [5, 3, 4, 0, 1],
       [7, 0, 3, 1, 4]])

# 数组的运算

In [9]:
a = np.random.randint(10,size=20).reshape(4,5)

In [10]:
b = np.random.randint(10,size=20).reshape(4,5)

In [11]:
a

array([[0, 0, 4, 1, 3],
       [3, 4, 1, 6, 8],
       [8, 3, 2, 4, 6],
       [5, 4, 9, 4, 9]])

In [12]:
b

array([[1, 3, 5, 6, 0],
       [9, 7, 4, 8, 5],
       [0, 1, 0, 2, 8],
       [3, 0, 1, 5, 0]])

In [13]:
a+b

array([[ 1,  3,  9,  7,  3],
       [12, 11,  5, 14, 13],
       [ 8,  4,  2,  6, 14],
       [ 8,  4, 10,  9,  9]])

In [15]:
a*b

array([[ 0,  0, 20,  6,  0],
       [27, 28,  4, 48, 40],
       [ 0,  3,  0,  8, 48],
       [15,  0,  9, 20,  0]])

In [16]:
a/b # b 中有0

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.        , 0.        , 0.8       , 0.16666667,        inf],
       [0.33333333, 0.57142857, 0.25      , 0.75      , 1.6       ],
       [       inf, 3.        ,        inf, 2.        , 0.75      ],
       [1.66666667,        inf, 9.        , 0.8       ,        inf]])

In [17]:
# 矩阵

In [18]:
np.mat([[1,3,4],[3,5,5]])

matrix([[1, 3, 4],
        [3, 5, 5]])

In [19]:
# 数组转换成矩阵

In [20]:
np.mat(a)

matrix([[0, 0, 4, 1, 3],
        [3, 4, 1, 6, 8],
        [8, 3, 2, 4, 6],
        [5, 4, 9, 4, 9]])

In [22]:
# 矩阵的 运算

In [23]:
A = np.mat(a)

In [24]:
B = np.mat(b)

In [26]:
A

matrix([[0, 0, 4, 1, 3],
        [3, 4, 1, 6, 8],
        [8, 3, 2, 4, 6],
        [5, 4, 9, 4, 9]])

In [27]:
B

matrix([[1, 3, 5, 6, 0],
        [9, 7, 4, 8, 5],
        [0, 1, 0, 2, 8],
        [3, 0, 1, 5, 0]])

In [28]:
A+B

matrix([[ 1,  3,  9,  7,  3],
        [12, 11,  5, 14, 13],
        [ 8,  4,  2,  6, 14],
        [ 8,  4, 10,  9,  9]])

In [29]:
# A 矩阵的行数要和B 矩阵的列数相同才可以

In [30]:
A*B

ValueError: shapes (4,5) and (4,5) not aligned: 5 (dim 1) != 4 (dim 0)

In [31]:
a = np.mat(np.random.randint(10,size=20).reshape(4,5))

In [32]:
b = np.mat(np.random.randint(10,size=20).reshape(5,4))

In [34]:
a*b

matrix([[167, 149,  52, 131],
        [ 86, 102,  34,  86],
        [112, 120,  31, 113],
        [123, 164,  30,  94]])

# array 常用函数

In [36]:
a=np.random.randint(10,size=20).reshape(4,5)

In [37]:
a

array([[1, 6, 6, 3, 4],
       [0, 7, 6, 7, 0],
       [7, 3, 6, 3, 2],
       [2, 1, 9, 8, 7]])

In [39]:
np.unique(a) #返回唯一值

array([0, 1, 2, 3, 4, 6, 7, 8, 9])

In [41]:
sum(a) # 所有列的和

array([10, 17, 27, 21, 13])

In [42]:
sum(a[0]) # 取行的和[1, 6, 6, 3, 4]

20

In [43]:
sum(a[:,0]) #取列的值的和

10

In [45]:
a.max()

9

In [46]:
max(a[0])

6

In [47]:
max(a[:,2])

9